[project]
name = "fe"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "plotly>=6.0.1",
    "schemadict>=0.0.12",
    "streamlit>=1.44.1",
]
